#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build OpenWrt

on:
  schedule:
    - cron: 0 23 * * *
#  release:
#    types: [published]
#  push:
#    branches:
#    - master
#    paths:
#    - 'new3.config'
  watch:
    types: [started]

env:
  REPO_URL: https://github.com/Lienol/openwrt.git
  REPO_BRANCH: dev-19.07
  D_CONFIG: new3.config
  DIY_SH: diy.sh
  FREE_UP_DISK: false
  SSH_ACTIONS: false
  UPLOAD_CONFIG: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: false
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build-openwrt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/*
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
        curl -fsSL https://raw.githubusercontent.com/P3TERX/dotfiles/master/.bashrc >> ~/.bashrc

    - name: Free up disk space
      if: env.FREE_UP_DISK == 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet
        docker rmi `docker images -q`
        sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Clone source code
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds clean && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        [ -e files ] && cp -rf files openwrt/files
        [ -e $D_CONFIG ] && cp -f $D_CONFIG openwrt/.config
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Create config directory
      if: env.UPLOAD_CONFIG == 'true'
      run: |
        cd openwrt
        mkdir -p upload
        cp -f $CONFIG_FILE upload
        ./scripts/diffconfig.sh > upload/diffconfig

    - name: Upload config directory
      uses: actions/upload-artifact@master
      if: env.UPLOAD_CONFIG == 'true'
      with:
        name: OpenWrt_config
        path: openwrt/upload

    - name: Download package
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        mkdir -p bin && touch bin/.temp.txt
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin
        path: openwrt/bin

    - name: Organize files
      id: organize
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        mkdir -p ${GITHUB_WORKSPACE}/firmware-squashfs-sysupgrade
        [ -e *squashfs-sysupgrade.bin ] && cp *squashfs-sysupgrade.bin ${GITHUB_WORKSPACE}/firmware-squashfs-sysupgrade
        if [ -e *.seed ]; then
          cp *.seed ${GITHUB_WORKSPACE}/firmware-squashfs-sysupgrade
        else
          cp ${GITHUB_WORKSPACE}/openwrt/.config ${GITHUB_WORKSPACE}/firmware-squashfs-sysupgrade/config.seed
        fi
        echo "::set-env name=FIRMWARE::$(pwd)"
        echo "::set-env name=SQUASHFS_SYSUPGRADE_DIR::${GITHUB_WORKSPACE}/firmware-squashfs-sysupgrade"
        echo "::set-env name=RELEASE_TAG::"$(TZ=UTC-8 date +"%Y.%m.%d")""
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      with:
        name: OpenWrt_firmware
        path: ${{ env.SQUASHFS_SYSUPGRADE_DIR }}

    - name: Upload to release
      uses: 1005789164/action-release@master
      with:
        token: ${{ secrets.OPENWRT_TOKEN }}
        gzip: false
        files: >
          firmware-squashfs-sysupgrade/*squashfs-sysupgrade.bin
          firmware-squashfs-sysupgrade/*.seed
        allow_override: true

    - name: Push firmware
      env:
        PUSH_TOKEN: ${{ secrets.OPENWRT_TOKEN }}
      run: |
        cd firmware-squashfs-sysupgrade
        [ -e *squashfs-sysupgrade.bin ] && mv *squashfs-sysupgrade.bin ${RELEASE_TAG}.bin
        [ -e *.seed ] && mv *.seed ${RELEASE_TAG}.seed
        ls -al
        git init
        git config --local user.email "fuck@github.com"
        git config --local user.name "FUCK"
        git add -f ./
        git commit -m ".bin and .seed"
        git push --force --quiet https://${PUSH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:firmware
        